compile:
  libraries:
    - arduino-mqtt
    - RadioLib
    - lora-serialization
  platforms:
    - esp32
    - esp8266

unittest:
  libraries:
    - arduino-mqtt
    - RadioLib
    - lora-serialization
  platforms:
    - esp32
    - esp8266
