compile:
  libraries:
    - mqtt
    - RadioLib
    - LoRa Serialization
  platforms:
    - esp32
    - esp8266

unittest:
  libraries:
    - mqtt
    - RadioLib
    - LoRa Serialization
  platforms:
    - esp32
    - esp8266
