name: hawk
on:
  push:
    branches:
      - 'merbanan/rtl_433/master'
    paths:
      - '/src/devices/bresser_5in1.c'
      - '/src/devices/bresser_6in1.c'

jobs:
  hawk:
    name: hawk
    runs-on: ubuntu-latest
    
    steps:
    - name: CommitHawk
      uses: jesalg/commit-hawk-action@v1.1
      with:
        slack_webhook_url: 'https://hooks.slack.com/services/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'
        slack_message: 'Contents of merbanan/rtl_433/*/bresser_?in1.c were changed'
